-- Long-running approval transaction (documentation only — executed programmatically in Python)
--
-- Opens a connection, begins a transaction, runs a trivial query, then holds
-- the connection idle-in-transaction for a configurable duration while awaiting
-- approval.
--
-- Python implementation:
--   conn = pool.getconn()
--   conn.autocommit = False
--   cur = conn.cursor()
--   cur.execute("SELECT 1")
--   shutdown_event.wait(timeout=random.uniform(30, 120))  # idle-in-transaction
--   conn.rollback()
--   pool.putconn(conn)
--
-- This creates sessions visible in pg_stat_activity with state = 'idle in transaction',
-- consuming connection slots in both PostgreSQL and PgBouncer.
