{{- if and (eq .Values.mode "trouble") .Values.trouble.controlApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-business-app.fullname" . }}
  labels:
    {{- include "my-business-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "my-business-app.selectorLabels" . | nindent 4 }}
{{- end }}
